<?php
 $form->setAttribute('action', $this->url('etunote', array('action' => 'add')));
 $form->prepare();
 
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
?>
<table>
        <tr>
            <td>Titre</td>
            <td> 
                <?php  echo $this->formRow($form->get('nom'));?>
            </td>
        </tr>

        <tr>
            <td>Auteur</td>
            <td><?php echo $this->formRow($form->get('prenom')); ?></td>
        </tr>
        
</table>
 <?php
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 
 //echo $this->formCollection($form);