<?php
// module/Album/view/album/album/index.phtml:

$title = 'etudiants';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('etunote', array('action'=>'add'));?>">Add new students</a>
</p>

<table class="table">
<tr>
    <th>nom</th>
    <th>prénom</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($etudiants as $e) : ?>
<tr>
    <td><?php echo $this->escapeHtml($e->nom);?></td>
    <td><?php echo $this->escapeHtml($e->prenom);?></td>
    <td>
        <a href="<?php echo $this->url('etunote', array('action'=>'editnote','id'=> $e->id));?>">Afficher note</a>
        <a href="<?php echo $this->url('etunote', array('action'=>'addnote','id'=> $e->id));?>">Ajouter note</a>
    </td>
</tr>
<?php endforeach; ?>
</table>

